"""add negligible severity level

Revision ID: 6ebcc32c2f68
Revises: d067794f5051
Create Date: 2026-06-30 11:08:45.622528

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6ebcc32c2f68'
down_revision: Union[str, None] = 'd067794f5051'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.alter_column('severity',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('INFO', 'NEGLIGIBLE', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.alter_column('severity',
               existing_type=sa.Enum('INFO', 'NEGLIGIBLE', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)

    # ### end Alembic commands ###
