"""initial

Revision ID: d067794f5051
Revises: 
Create Date: 2026-06-27 13:52:58.562505

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd067794f5051'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exploit_db_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cve_ids', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('exploit_type', sa.String(length=32), nullable=True),
    sa.Column('platform', sa.String(length=64), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.Date(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kev_entries',
    sa.Column('cve_id', sa.String(length=32), nullable=False),
    sa.Column('vendor_project', sa.Text(), nullable=True),
    sa.Column('product', sa.Text(), nullable=True),
    sa.Column('vulnerability_name', sa.Text(), nullable=True),
    sa.Column('date_added', sa.Date(), nullable=True),
    sa.Column('known_ransomware', sa.Boolean(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('cve_id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('repo_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sbom_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scan_run_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_cyclonedx', sa.JSON(), nullable=False),
    sa.Column('component_count', sa.Integer(), nullable=False),
    sa.Column('syft_version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_run_id')
    )
    op.create_table('components',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=128), nullable=False),
    sa.Column('ecosystem', sa.String(length=64), nullable=False),
    sa.Column('purl', sa.Text(), nullable=False),
    sa.Column('cpe', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['sbom_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'purl', name='uq_component_snapshot_purl')
    )
    with op.batch_alter_table('components', schema=None) as batch_op:
        batch_op.create_index('ix_component_ecosystem_name_version', ['ecosystem', 'name', 'version'], unique=False)

    op.create_table('findings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('component_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('cve_id', sa.String(length=32), nullable=False),
    sa.Column('cvss_score', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('cvss_vector', sa.String(length=128), nullable=True),
    sa.Column('severity', sa.Enum('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity'), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('fix_version', sa.String(length=128), nullable=True),
    sa.Column('reachability_status', sa.Enum('NOT_ANALYZED', 'REACHABLE', 'NOT_REACHABLE', 'UNCERTAIN', name='reachabilitystatus'), nullable=False),
    sa.Column('reachability_rationale', sa.Text(), nullable=True),
    sa.Column('reachability_agent_used', sa.Boolean(), nullable=False),
    sa.Column('exploit_availability', sa.Enum('UNKNOWN', 'NO_KNOWN_EXPLOIT', 'POC_EXISTS', 'WEAPONIZED', name='exploitavailability'), nullable=False),
    sa.Column('exploit_details', sa.Text(), nullable=True),
    sa.Column('triage_status', sa.Enum('NOT_ANALYZED', 'TRIAGED_ACCEPTED', 'TRIAGED_FP', 'TRIAGED_DEFERRED', name='triagestatus'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['sbom_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('component_id', 'cve_id', name='uq_finding_component_cve')
    )
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.create_index('ix_finding_snapshot_reachability', ['snapshot_id', 'reachability_status'], unique=False)
        batch_op.create_index('ix_finding_snapshot_severity', ['snapshot_id', 'severity'], unique=False)

    op.create_table('triage_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('finding_id', sa.Uuid(), nullable=False),
    sa.Column('old_status', sa.Enum('NOT_ANALYZED', 'TRIAGED_ACCEPTED', 'TRIAGED_FP', 'TRIAGED_DEFERRED', name='triagestatus'), nullable=False),
    sa.Column('new_status', sa.Enum('NOT_ANALYZED', 'TRIAGED_ACCEPTED', 'TRIAGED_FP', 'TRIAGED_DEFERRED', name='triagestatus'), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.String(length=255), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('triage_history')
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_index('ix_finding_snapshot_severity')
        batch_op.drop_index('ix_finding_snapshot_reachability')

    op.drop_table('findings')
    with op.batch_alter_table('components', schema=None) as batch_op:
        batch_op.drop_index('ix_component_ecosystem_name_version')

    op.drop_table('components')
    op.drop_table('sbom_snapshots')
    op.drop_table('projects')
    op.drop_table('kev_entries')
    op.drop_table('exploit_db_entries')
    # ### end Alembic commands ###
